spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro-db?characterEncoding=utf-8&useSSL=false
    username: root
    password: 806823
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
shiro:
  # shiro \u767B\u5F55\u7684\u5165\u53E3\u8DEF\u5F84
  loginUrl: /myController/login
